//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SanMarIntegration.com.sanmar.ws_orderstatusservice {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="OrderStatusServiceBinding", Namespace="http://www.promostandards.org/WSDL/OrderStatusService/1.0.0/")]
    public partial class OrderStatusService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getOrderStatusDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getOrderStatusTypesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public OrderStatusService() {
            this.Url = global::SanMarIntegration.Properties.Settings.Default.SanMarIntegration_com_sanmar_ws_orderstatusservice_OrderStatusService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getOrderStatusDetailsCompletedEventHandler getOrderStatusDetailsCompleted;
        
        /// <remarks/>
        public event getOrderStatusTypesCompletedEventHandler getOrderStatusTypesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("getOrderStatusDetails", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetOrderStatusDetailsResponse", Namespace="http://www.promostandards.org/WSDL/OrderStatusService/1.0.0/")]
        public GetOrderStatusDetailsResponse getOrderStatusDetails([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/OrderStatusService/1.0.0/")] GetOrderStatusDetailsRequest GetOrderStatusDetailsRequest) {
            object[] results = this.Invoke("getOrderStatusDetails", new object[] {
                        GetOrderStatusDetailsRequest});
            return ((GetOrderStatusDetailsResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getOrderStatusDetailsAsync(GetOrderStatusDetailsRequest GetOrderStatusDetailsRequest) {
            this.getOrderStatusDetailsAsync(GetOrderStatusDetailsRequest, null);
        }
        
        /// <remarks/>
        public void getOrderStatusDetailsAsync(GetOrderStatusDetailsRequest GetOrderStatusDetailsRequest, object userState) {
            if ((this.getOrderStatusDetailsOperationCompleted == null)) {
                this.getOrderStatusDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetOrderStatusDetailsOperationCompleted);
            }
            this.InvokeAsync("getOrderStatusDetails", new object[] {
                        GetOrderStatusDetailsRequest}, this.getOrderStatusDetailsOperationCompleted, userState);
        }
        
        private void OngetOrderStatusDetailsOperationCompleted(object arg) {
            if ((this.getOrderStatusDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getOrderStatusDetailsCompleted(this, new getOrderStatusDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("getOrderStatusTypes", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetOrderStatusTypesResponse", Namespace="http://www.promostandards.org/WSDL/OrderStatusService/1.0.0/")]
        public GetOrderStatusTypesResponse getOrderStatusTypes([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/OrderStatusService/1.0.0/")] GetOrderStatusTypesRequest GetOrderStatusTypesRequest) {
            object[] results = this.Invoke("getOrderStatusTypes", new object[] {
                        GetOrderStatusTypesRequest});
            return ((GetOrderStatusTypesResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getOrderStatusTypesAsync(GetOrderStatusTypesRequest GetOrderStatusTypesRequest) {
            this.getOrderStatusTypesAsync(GetOrderStatusTypesRequest, null);
        }
        
        /// <remarks/>
        public void getOrderStatusTypesAsync(GetOrderStatusTypesRequest GetOrderStatusTypesRequest, object userState) {
            if ((this.getOrderStatusTypesOperationCompleted == null)) {
                this.getOrderStatusTypesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetOrderStatusTypesOperationCompleted);
            }
            this.InvokeAsync("getOrderStatusTypes", new object[] {
                        GetOrderStatusTypesRequest}, this.getOrderStatusTypesOperationCompleted, userState);
        }
        
        private void OngetOrderStatusTypesOperationCompleted(object arg) {
            if ((this.getOrderStatusTypesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getOrderStatusTypesCompleted(this, new getOrderStatusTypesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/OrderStatusService/1.0.0/")]
    public partial class GetOrderStatusDetailsRequest {
        
        private string wsVersionField;
        
        private string idField;
        
        private string passwordField;
        
        private int queryTypeField;
        
        private string referenceNumberField;
        
        private System.Nullable<System.DateTime> statusTimeStampField;
        
        private bool statusTimeStampFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        public string wsVersion {
            get {
                return this.wsVersionField;
            }
            set {
                this.wsVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public int queryType {
            get {
                return this.queryTypeField;
            }
            set {
                this.queryTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        public string referenceNumber {
            get {
                return this.referenceNumberField;
            }
            set {
                this.referenceNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> statusTimeStamp {
            get {
                return this.statusTimeStampField;
            }
            set {
                this.statusTimeStampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusTimeStampSpecified {
            get {
                return this.statusTimeStampFieldSpecified;
            }
            set {
                this.statusTimeStampFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/OrderStatusService/1.0.0/")]
    public partial class GetOrderStatusDetailsResponse {
        
        private GetOrderStatusDetailsResponseOrderStatus[] orderStatusArrayField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("OrderStatus", IsNullable=false)]
        public GetOrderStatusDetailsResponseOrderStatus[] OrderStatusArray {
            get {
                return this.orderStatusArrayField;
            }
            set {
                this.orderStatusArrayField = value;
            }
        }
        
        /// <remarks/>
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/OrderStatusService/1.0.0/")]
    public partial class GetOrderStatusDetailsResponseOrderStatus {
        
        private string purchaseOrderNumberField;
        
        private GetOrderStatusDetailsResponseOrderStatusOrderStatusDetail[] orderStatusDetailArrayField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        public string purchaseOrderNumber {
            get {
                return this.purchaseOrderNumberField;
            }
            set {
                this.purchaseOrderNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("OrderStatusDetail", IsNullable=false)]
        public GetOrderStatusDetailsResponseOrderStatusOrderStatusDetail[] OrderStatusDetailArray {
            get {
                return this.orderStatusDetailArrayField;
            }
            set {
                this.orderStatusDetailArrayField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/OrderStatusService/1.0.0/")]
    public partial class GetOrderStatusDetailsResponseOrderStatusOrderStatusDetail {
        
        private string factoryOrderNumberField;
        
        private GetOrderStatusDetailsResponseOrderStatusOrderStatusDetailStatusID statusIDField;
        
        private string statusNameField;
        
        private System.Nullable<System.DateTime> expectedShipDateField;
        
        private bool expectedShipDateFieldSpecified;
        
        private System.Nullable<System.DateTime> expectedDeliveryDateField;
        
        private bool expectedDeliveryDateFieldSpecified;
        
        private GetOrderStatusDetailsResponseOrderStatusOrderStatusDetailRespondTo[] responseToArrayField;
        
        private string additionalExplanationField;
        
        private bool responseRequiredField;
        
        private bool responseRequiredFieldSpecified;
        
        private System.DateTime validTimestampField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        public string factoryOrderNumber {
            get {
                return this.factoryOrderNumberField;
            }
            set {
                this.factoryOrderNumberField = value;
            }
        }
        
        /// <remarks/>
        public GetOrderStatusDetailsResponseOrderStatusOrderStatusDetailStatusID statusID {
            get {
                return this.statusIDField;
            }
            set {
                this.statusIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        public string statusName {
            get {
                return this.statusNameField;
            }
            set {
                this.statusNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> expectedShipDate {
            get {
                return this.expectedShipDateField;
            }
            set {
                this.expectedShipDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool expectedShipDateSpecified {
            get {
                return this.expectedShipDateFieldSpecified;
            }
            set {
                this.expectedShipDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> expectedDeliveryDate {
            get {
                return this.expectedDeliveryDateField;
            }
            set {
                this.expectedDeliveryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool expectedDeliveryDateSpecified {
            get {
                return this.expectedDeliveryDateFieldSpecified;
            }
            set {
                this.expectedDeliveryDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("RespondTo", IsNullable=false)]
        public GetOrderStatusDetailsResponseOrderStatusOrderStatusDetailRespondTo[] ResponseToArray {
            get {
                return this.responseToArrayField;
            }
            set {
                this.responseToArrayField = value;
            }
        }
        
        /// <remarks/>
        public string additionalExplanation {
            get {
                return this.additionalExplanationField;
            }
            set {
                this.additionalExplanationField = value;
            }
        }
        
        /// <remarks/>
        public bool responseRequired {
            get {
                return this.responseRequiredField;
            }
            set {
                this.responseRequiredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool responseRequiredSpecified {
            get {
                return this.responseRequiredFieldSpecified;
            }
            set {
                this.responseRequiredFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime validTimestamp {
            get {
                return this.validTimestampField;
            }
            set {
                this.validTimestampField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/OrderStatusService/1.0.0/")]
    public enum GetOrderStatusDetailsResponseOrderStatusOrderStatusDetailStatusID {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("10")]
        Item10,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("11")]
        Item11,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("20")]
        Item20,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("20")]
        Item201,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("30")]
        Item30,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("40")]
        Item40,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("41")]
        Item41,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("42")]
        Item42,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("43")]
        Item43,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("44")]
        Item44,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("60")]
        Item60,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("70")]
        Item70,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("75")]
        Item75,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("80")]
        Item80,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("99")]
        Item99,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/OrderStatusService/1.0.0/")]
    public partial class GetOrderStatusDetailsResponseOrderStatusOrderStatusDetailRespondTo {
        
        private string nameField;
        
        private string emailAddressField;
        
        private string phoneNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        public string emailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        public string phoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/OrderStatusService/1.0.0/")]
    public partial class GetOrderStatusTypesRequest {
        
        private string wsVersionField;
        
        private string idField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        public string wsVersion {
            get {
                return this.wsVersionField;
            }
            set {
                this.wsVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/OrderStatusService/1.0.0/")]
    public partial class GetOrderStatusTypesResponse {
        
        private GetOrderStatusTypesResponseStatus[] statusArrayField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Status", IsNullable=false)]
        public GetOrderStatusTypesResponseStatus[] StatusArray {
            get {
                return this.statusArrayField;
            }
            set {
                this.statusArrayField = value;
            }
        }
        
        /// <remarks/>
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/OrderStatusService/1.0.0/")]
    public partial class GetOrderStatusTypesResponseStatus {
        
        private int idField;
        
        private string nameField;
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void getOrderStatusDetailsCompletedEventHandler(object sender, getOrderStatusDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getOrderStatusDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getOrderStatusDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetOrderStatusDetailsResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetOrderStatusDetailsResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void getOrderStatusTypesCompletedEventHandler(object sender, getOrderStatusTypesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getOrderStatusTypesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getOrderStatusTypesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetOrderStatusTypesResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetOrderStatusTypesResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591