//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace BlueGenerationsIntegration.com.bluegeneration.promostandards_promoinventoryservice {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_InventoryService", Namespace="http://tempuri.org/")]
    public partial class BasicHttpBinding_InventoryService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getFilterValuesOperationCompleted;
        
        private System.Threading.SendOrPostCallback getInventoryLevelsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BasicHttpBinding_InventoryService() {
            this.Url = global::BlueGenerationsIntegration.Properties.Settings.Default.BlueGenerationsIntegration_com_bluegeneration_promostandards_promoinventoryservice_PromoInventoryService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getFilterValuesCompletedEventHandler getFilterValuesCompleted;
        
        /// <remarks/>
        public event getInventoryLevelsCompletedEventHandler getInventoryLevelsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("getFilterValues", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetFilterValuesResponse", Namespace="http://www.promostandards.org/WSDL/Inventory/2.0.0/")]
        public GetFilterValuesResponse getFilterValues([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/Inventory/2.0.0/")] GetFilterValuesRequest GetFilterValuesRequest) {
            object[] results = this.Invoke("getFilterValues", new object[] {
                        GetFilterValuesRequest});
            return ((GetFilterValuesResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getFilterValuesAsync(GetFilterValuesRequest GetFilterValuesRequest) {
            this.getFilterValuesAsync(GetFilterValuesRequest, null);
        }
        
        /// <remarks/>
        public void getFilterValuesAsync(GetFilterValuesRequest GetFilterValuesRequest, object userState) {
            if ((this.getFilterValuesOperationCompleted == null)) {
                this.getFilterValuesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetFilterValuesOperationCompleted);
            }
            this.InvokeAsync("getFilterValues", new object[] {
                        GetFilterValuesRequest}, this.getFilterValuesOperationCompleted, userState);
        }
        
        private void OngetFilterValuesOperationCompleted(object arg) {
            if ((this.getFilterValuesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getFilterValuesCompleted(this, new getFilterValuesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("getInventoryLevels", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetInventoryLevelsResponse", Namespace="http://www.promostandards.org/WSDL/Inventory/2.0.0/")]
        public GetInventoryLevelsResponse getInventoryLevels([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/Inventory/2.0.0/")] GetInventoryLevelsRequest GetInventoryLevelsRequest) {
            object[] results = this.Invoke("getInventoryLevels", new object[] {
                        GetInventoryLevelsRequest});
            return ((GetInventoryLevelsResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getInventoryLevelsAsync(GetInventoryLevelsRequest GetInventoryLevelsRequest) {
            this.getInventoryLevelsAsync(GetInventoryLevelsRequest, null);
        }
        
        /// <remarks/>
        public void getInventoryLevelsAsync(GetInventoryLevelsRequest GetInventoryLevelsRequest, object userState) {
            if ((this.getInventoryLevelsOperationCompleted == null)) {
                this.getInventoryLevelsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetInventoryLevelsOperationCompleted);
            }
            this.InvokeAsync("getInventoryLevels", new object[] {
                        GetInventoryLevelsRequest}, this.getInventoryLevelsOperationCompleted, userState);
        }
        
        private void OngetInventoryLevelsOperationCompleted(object arg) {
            if ((this.getInventoryLevelsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getInventoryLevelsCompleted(this, new getInventoryLevelsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    // CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpsBinding_InventoryService", Namespace="http://tempuri.org/")]
    public partial class BasicHttpsBinding_InventoryService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getFilterValuesOperationCompleted;
        
        private System.Threading.SendOrPostCallback getInventoryLevelsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BasicHttpsBinding_InventoryService() {
            this.Url = "https://promostandards.bluegeneration.com/Services/PromoInventoryService.svc";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getFilterValuesCompletedEventHandler getFilterValuesCompleted;
        
        /// <remarks/>
        public event getInventoryLevelsCompletedEventHandler getInventoryLevelsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("getFilterValues", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetFilterValuesResponse", Namespace="http://www.promostandards.org/WSDL/Inventory/2.0.0/")]
        public GetFilterValuesResponse getFilterValues([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/Inventory/2.0.0/")] GetFilterValuesRequest GetFilterValuesRequest) {
            object[] results = this.Invoke("getFilterValues", new object[] {
                        GetFilterValuesRequest});
            return ((GetFilterValuesResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getFilterValuesAsync(GetFilterValuesRequest GetFilterValuesRequest) {
            this.getFilterValuesAsync(GetFilterValuesRequest, null);
        }
        
        /// <remarks/>
        public void getFilterValuesAsync(GetFilterValuesRequest GetFilterValuesRequest, object userState) {
            if ((this.getFilterValuesOperationCompleted == null)) {
                this.getFilterValuesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetFilterValuesOperationCompleted);
            }
            this.InvokeAsync("getFilterValues", new object[] {
                        GetFilterValuesRequest}, this.getFilterValuesOperationCompleted, userState);
        }
        
        private void OngetFilterValuesOperationCompleted(object arg) {
            if ((this.getFilterValuesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getFilterValuesCompleted(this, new getFilterValuesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("getInventoryLevels", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetInventoryLevelsResponse", Namespace="http://www.promostandards.org/WSDL/Inventory/2.0.0/")]
        public GetInventoryLevelsResponse getInventoryLevels([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/Inventory/2.0.0/")] GetInventoryLevelsRequest GetInventoryLevelsRequest) {
            object[] results = this.Invoke("getInventoryLevels", new object[] {
                        GetInventoryLevelsRequest});
            return ((GetInventoryLevelsResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getInventoryLevelsAsync(GetInventoryLevelsRequest GetInventoryLevelsRequest) {
            this.getInventoryLevelsAsync(GetInventoryLevelsRequest, null);
        }
        
        /// <remarks/>
        public void getInventoryLevelsAsync(GetInventoryLevelsRequest GetInventoryLevelsRequest, object userState) {
            if ((this.getInventoryLevelsOperationCompleted == null)) {
                this.getInventoryLevelsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetInventoryLevelsOperationCompleted);
            }
            this.InvokeAsync("getInventoryLevels", new object[] {
                        GetInventoryLevelsRequest}, this.getInventoryLevelsOperationCompleted, userState);
        }
        
        private void OngetInventoryLevelsOperationCompleted(object arg) {
            if ((this.getInventoryLevelsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getInventoryLevelsCompleted(this, new getInventoryLevelsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/Inventory/2.0.0/")]
    public partial class GetFilterValuesRequest {
        
        private wsVersion wsVersionField;
        
        private string idField;
        
        private string passwordField;
        
        private string productIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/Inventory/2.0.0/SharedObjects/")]
        public wsVersion wsVersion {
            get {
                return this.wsVersionField;
            }
            set {
                this.wsVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/Inventory/2.0.0/SharedObjects/")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/Inventory/2.0.0/SharedObjects/")]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/Inventory/2.0.0/SharedObjects/")]
        public string productId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.promostandards.org/WSDL/Inventory/2.0.0/SharedObjects/")]
    public enum wsVersion {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2.0.0")]
        Item200,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/Inventory/2.0.0/")]
    public partial class GetFilterValuesResponse {
        
        private GetFilterValuesResponseFilterValues filterValuesField;
        
        private ArrayOfServiceMessageServiceMessage[] serviceMessageArrayField;
        
        /// <remarks/>
        public GetFilterValuesResponseFilterValues FilterValues {
            get {
                return this.filterValuesField;
            }
            set {
                this.filterValuesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="http://www.promostandards.org/WSDL/Inventory/2.0.0/SharedObjects/")]
        [System.Xml.Serialization.XmlArrayItemAttribute("ServiceMessage", IsNullable=false)]
        public ArrayOfServiceMessageServiceMessage[] ServiceMessageArray {
            get {
                return this.serviceMessageArrayField;
            }
            set {
                this.serviceMessageArrayField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/Inventory/2.0.0/")]
    public partial class GetFilterValuesResponseFilterValues {
        
        private string productIdField;
        
        private Filter filterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/Inventory/2.0.0/SharedObjects/")]
        public string productId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/Inventory/2.0.0/SharedObjects/")]
        public Filter Filter {
            get {
                return this.filterField;
            }
            set {
                this.filterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/Inventory/2.0.0/SharedObjects/")]
    public partial class Filter {
        
        private string[] partIdArrayField;
        
        private labelSize[] labelSizeArrayField;
        
        private string[] partColorArrayField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("partId", IsNullable=false)]
        public string[] partIdArray {
            get {
                return this.partIdArrayField;
            }
            set {
                this.partIdArrayField = value;
            }
        }
        
        /// <remarks/>
        public labelSize[] LabelSizeArray {
            get {
                return this.labelSizeArrayField;
            }
            set {
                this.labelSizeArrayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("partColor", IsNullable=false)]
        public string[] PartColorArray {
            get {
                return this.partColorArrayField;
            }
            set {
                this.partColorArrayField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.promostandards.org/WSDL/Inventory/2.0.0/SharedObjects/")]
    public enum labelSize {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2XL")]
        Item2XL,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2XS")]
        Item2XS,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3XL")]
        Item3XL,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3XS")]
        Item3XS,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4XL")]
        Item4XL,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4XS")]
        Item4XS,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5XL")]
        Item5XL,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5XS")]
        Item5XS,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6XL")]
        Item6XL,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6XS")]
        Item6XS,
        
        /// <remarks/>
        CUSTOM,
        
        /// <remarks/>
        L,
        
        /// <remarks/>
        M,
        
        /// <remarks/>
        OSFA,
        
        /// <remarks/>
        S,
        
        /// <remarks/>
        XL,
        
        /// <remarks/>
        XS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/Inventory/2.0.0/SharedObjects/")]
    public partial class ArrayOfServiceMessageServiceMessage {
        
        private int codeField;
        
        private string descriptionField;
        
        private ServiceMessageSeverity severityField;
        
        /// <remarks/>
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public ServiceMessageSeverity severity {
            get {
                return this.severityField;
            }
            set {
                this.severityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.promostandards.org/WSDL/Inventory/2.0.0/SharedObjects/")]
    public enum ServiceMessageSeverity {
        
        /// <remarks/>
        Error,
        
        /// <remarks/>
        Information,
        
        /// <remarks/>
        Warning,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/Inventory/2.0.0/")]
    public partial class GetInventoryLevelsRequest {
        
        private wsVersion wsVersionField;
        
        private string idField;
        
        private string passwordField;
        
        private string productIdField;
        
        private Filter filterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/Inventory/2.0.0/SharedObjects/")]
        public wsVersion wsVersion {
            get {
                return this.wsVersionField;
            }
            set {
                this.wsVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/Inventory/2.0.0/SharedObjects/")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/Inventory/2.0.0/SharedObjects/")]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/Inventory/2.0.0/SharedObjects/")]
        public string productId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/Inventory/2.0.0/SharedObjects/")]
        public Filter Filter {
            get {
                return this.filterField;
            }
            set {
                this.filterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/Inventory/2.0.0/")]
    public partial class GetInventoryLevelsResponse {
        
        private Inventory inventoryField;
        
        private ArrayOfServiceMessageServiceMessage[] serviceMessageArrayField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/Inventory/2.0.0/SharedObjects/")]
        public Inventory Inventory {
            get {
                return this.inventoryField;
            }
            set {
                this.inventoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="http://www.promostandards.org/WSDL/Inventory/2.0.0/SharedObjects/")]
        [System.Xml.Serialization.XmlArrayItemAttribute("ServiceMessage", IsNullable=false)]
        public ArrayOfServiceMessageServiceMessage[] ServiceMessageArray {
            get {
                return this.serviceMessageArrayField;
            }
            set {
                this.serviceMessageArrayField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/Inventory/2.0.0/SharedObjects/")]
    public partial class Inventory {
        
        private string productIdField;
        
        private ArrayOfPartInventoryArrayPartInventoryPartInventory[] partInventoryArrayField;
        
        /// <remarks/>
        public string productId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("PartInventory", IsNullable=false)]
        public ArrayOfPartInventoryArrayPartInventoryPartInventory[] PartInventoryArray {
            get {
                return this.partInventoryArrayField;
            }
            set {
                this.partInventoryArrayField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/Inventory/2.0.0/SharedObjects/")]
    public partial class ArrayOfPartInventoryArrayPartInventoryPartInventory {
        
        private string partIdField;
        
        private bool mainPartField;
        
        private string partColorField;
        
        private labelSize labelSizeField;
        
        private bool labelSizeFieldSpecified;
        
        private string partDescriptionField;
        
        private ArrayOfPartInventoryArrayPartInventoryPartInventoryQuantityAvailable quantityAvailableField;
        
        private bool manufacturedItemField;
        
        private bool buyToOrderField;
        
        private int replenishmentLeadTimeField;
        
        private bool replenishmentLeadTimeFieldSpecified;
        
        private string attributeSelectionField;
        
        private ArrayOfInventoryLocationInventoryLocation[] inventoryLocationArrayField;
        
        private System.DateTime lastModifiedField;
        
        private bool lastModifiedFieldSpecified;
        
        /// <remarks/>
        public string partId {
            get {
                return this.partIdField;
            }
            set {
                this.partIdField = value;
            }
        }
        
        /// <remarks/>
        public bool mainPart {
            get {
                return this.mainPartField;
            }
            set {
                this.mainPartField = value;
            }
        }
        
        /// <remarks/>
        public string partColor {
            get {
                return this.partColorField;
            }
            set {
                this.partColorField = value;
            }
        }
        
        /// <remarks/>
        public labelSize labelSize {
            get {
                return this.labelSizeField;
            }
            set {
                this.labelSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool labelSizeSpecified {
            get {
                return this.labelSizeFieldSpecified;
            }
            set {
                this.labelSizeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string partDescription {
            get {
                return this.partDescriptionField;
            }
            set {
                this.partDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public ArrayOfPartInventoryArrayPartInventoryPartInventoryQuantityAvailable quantityAvailable {
            get {
                return this.quantityAvailableField;
            }
            set {
                this.quantityAvailableField = value;
            }
        }
        
        /// <remarks/>
        public bool manufacturedItem {
            get {
                return this.manufacturedItemField;
            }
            set {
                this.manufacturedItemField = value;
            }
        }
        
        /// <remarks/>
        public bool buyToOrder {
            get {
                return this.buyToOrderField;
            }
            set {
                this.buyToOrderField = value;
            }
        }
        
        /// <remarks/>
        public int replenishmentLeadTime {
            get {
                return this.replenishmentLeadTimeField;
            }
            set {
                this.replenishmentLeadTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool replenishmentLeadTimeSpecified {
            get {
                return this.replenishmentLeadTimeFieldSpecified;
            }
            set {
                this.replenishmentLeadTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string attributeSelection {
            get {
                return this.attributeSelectionField;
            }
            set {
                this.attributeSelectionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("InventoryLocation", IsNullable=false)]
        public ArrayOfInventoryLocationInventoryLocation[] InventoryLocationArray {
            get {
                return this.inventoryLocationArrayField;
            }
            set {
                this.inventoryLocationArrayField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime lastModified {
            get {
                return this.lastModifiedField;
            }
            set {
                this.lastModifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lastModifiedSpecified {
            get {
                return this.lastModifiedFieldSpecified;
            }
            set {
                this.lastModifiedFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/Inventory/2.0.0/SharedObjects/")]
    public partial class ArrayOfPartInventoryArrayPartInventoryPartInventoryQuantityAvailable {
        
        private ArrayOfPartInventoryArrayPartInventoryPartInventoryQuantityAvailableQuantity quantityField;
        
        /// <remarks/>
        public ArrayOfPartInventoryArrayPartInventoryPartInventoryQuantityAvailableQuantity Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/Inventory/2.0.0/SharedObjects/")]
    public partial class ArrayOfPartInventoryArrayPartInventoryPartInventoryQuantityAvailableQuantity {
        
        private QuantityUom uomField;
        
        private decimal valueField;
        
        /// <remarks/>
        public QuantityUom uom {
            get {
                return this.uomField;
            }
            set {
                this.uomField = value;
            }
        }
        
        /// <remarks/>
        public decimal value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.promostandards.org/WSDL/Inventory/2.0.0/SharedObjects/")]
    public enum QuantityUom {
        
        /// <remarks/>
        BX,
        
        /// <remarks/>
        CA,
        
        /// <remarks/>
        DZ,
        
        /// <remarks/>
        EA,
        
        /// <remarks/>
        KT,
        
        /// <remarks/>
        PK,
        
        /// <remarks/>
        PR,
        
        /// <remarks/>
        RL,
        
        /// <remarks/>
        SL,
        
        /// <remarks/>
        ST,
        
        /// <remarks/>
        TH,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/Inventory/2.0.0/SharedObjects/")]
    public partial class ArrayOfInventoryLocationInventoryLocation {
        
        private string inventoryLocationIdField;
        
        private string inventoryLocationNameField;
        
        private string postalCodeField;
        
        private InventoryLocationCountry countryField;
        
        private bool countryFieldSpecified;
        
        private ArrayOfInventoryLocationInventoryLocationInventoryLocationQuantity inventoryLocationQuantityField;
        
        private ArrayOfFutureAvailabilityFutureAvailability[] futureAvailabilityArrayField;
        
        /// <remarks/>
        public string inventoryLocationId {
            get {
                return this.inventoryLocationIdField;
            }
            set {
                this.inventoryLocationIdField = value;
            }
        }
        
        /// <remarks/>
        public string inventoryLocationName {
            get {
                return this.inventoryLocationNameField;
            }
            set {
                this.inventoryLocationNameField = value;
            }
        }
        
        /// <remarks/>
        public string postalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        public InventoryLocationCountry country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool countrySpecified {
            get {
                return this.countryFieldSpecified;
            }
            set {
                this.countryFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public ArrayOfInventoryLocationInventoryLocationInventoryLocationQuantity inventoryLocationQuantity {
            get {
                return this.inventoryLocationQuantityField;
            }
            set {
                this.inventoryLocationQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("FutureAvailability", IsNullable=false)]
        public ArrayOfFutureAvailabilityFutureAvailability[] FutureAvailabilityArray {
            get {
                return this.futureAvailabilityArrayField;
            }
            set {
                this.futureAvailabilityArrayField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.codesynthesis.com/xmlns/xsstl")]
    public enum InventoryLocationCountry {
        
        /// <remarks/>
        AF,
        
        /// <remarks/>
        AX,
        
        /// <remarks/>
        AL,
        
        /// <remarks/>
        DZ,
        
        /// <remarks/>
        AS,
        
        /// <remarks/>
        AD,
        
        /// <remarks/>
        AO,
        
        /// <remarks/>
        AI,
        
        /// <remarks/>
        AQ,
        
        /// <remarks/>
        AG,
        
        /// <remarks/>
        AR,
        
        /// <remarks/>
        AM,
        
        /// <remarks/>
        AW,
        
        /// <remarks/>
        AU,
        
        /// <remarks/>
        AT,
        
        /// <remarks/>
        AZ,
        
        /// <remarks/>
        BS,
        
        /// <remarks/>
        BH,
        
        /// <remarks/>
        BD,
        
        /// <remarks/>
        BB,
        
        /// <remarks/>
        BY,
        
        /// <remarks/>
        BE,
        
        /// <remarks/>
        BZ,
        
        /// <remarks/>
        BJ,
        
        /// <remarks/>
        BM,
        
        /// <remarks/>
        BT,
        
        /// <remarks/>
        BO,
        
        /// <remarks/>
        BA,
        
        /// <remarks/>
        BW,
        
        /// <remarks/>
        BV,
        
        /// <remarks/>
        BR,
        
        /// <remarks/>
        IO,
        
        /// <remarks/>
        BN,
        
        /// <remarks/>
        BG,
        
        /// <remarks/>
        BF,
        
        /// <remarks/>
        BI,
        
        /// <remarks/>
        KH,
        
        /// <remarks/>
        CM,
        
        /// <remarks/>
        CA,
        
        /// <remarks/>
        CV,
        
        /// <remarks/>
        KY,
        
        /// <remarks/>
        CF,
        
        /// <remarks/>
        TD,
        
        /// <remarks/>
        CL,
        
        /// <remarks/>
        CN,
        
        /// <remarks/>
        CX,
        
        /// <remarks/>
        CC,
        
        /// <remarks/>
        CO,
        
        /// <remarks/>
        KM,
        
        /// <remarks/>
        CG,
        
        /// <remarks/>
        CD,
        
        /// <remarks/>
        CK,
        
        /// <remarks/>
        CR,
        
        /// <remarks/>
        CI,
        
        /// <remarks/>
        HR,
        
        /// <remarks/>
        CU,
        
        /// <remarks/>
        CY,
        
        /// <remarks/>
        CZ,
        
        /// <remarks/>
        DK,
        
        /// <remarks/>
        DJ,
        
        /// <remarks/>
        DM,
        
        /// <remarks/>
        DO,
        
        /// <remarks/>
        EC,
        
        /// <remarks/>
        EG,
        
        /// <remarks/>
        SV,
        
        /// <remarks/>
        GQ,
        
        /// <remarks/>
        ER,
        
        /// <remarks/>
        EE,
        
        /// <remarks/>
        ET,
        
        /// <remarks/>
        FK,
        
        /// <remarks/>
        FO,
        
        /// <remarks/>
        FJ,
        
        /// <remarks/>
        FI,
        
        /// <remarks/>
        FR,
        
        /// <remarks/>
        GF,
        
        /// <remarks/>
        PF,
        
        /// <remarks/>
        TF,
        
        /// <remarks/>
        GA,
        
        /// <remarks/>
        GM,
        
        /// <remarks/>
        GE,
        
        /// <remarks/>
        DE,
        
        /// <remarks/>
        GH,
        
        /// <remarks/>
        GI,
        
        /// <remarks/>
        GR,
        
        /// <remarks/>
        GL,
        
        /// <remarks/>
        GD,
        
        /// <remarks/>
        GP,
        
        /// <remarks/>
        GU,
        
        /// <remarks/>
        GT,
        
        /// <remarks/>
        GG,
        
        /// <remarks/>
        GN,
        
        /// <remarks/>
        GW,
        
        /// <remarks/>
        GY,
        
        /// <remarks/>
        HT,
        
        /// <remarks/>
        HM,
        
        /// <remarks/>
        VA,
        
        /// <remarks/>
        HN,
        
        /// <remarks/>
        HK,
        
        /// <remarks/>
        HU,
        
        /// <remarks/>
        IS,
        
        /// <remarks/>
        IN,
        
        /// <remarks/>
        ID,
        
        /// <remarks/>
        IR,
        
        /// <remarks/>
        IQ,
        
        /// <remarks/>
        IE,
        
        /// <remarks/>
        IM,
        
        /// <remarks/>
        IL,
        
        /// <remarks/>
        IT,
        
        /// <remarks/>
        JM,
        
        /// <remarks/>
        JP,
        
        /// <remarks/>
        JE,
        
        /// <remarks/>
        JO,
        
        /// <remarks/>
        KZ,
        
        /// <remarks/>
        KE,
        
        /// <remarks/>
        KI,
        
        /// <remarks/>
        KP,
        
        /// <remarks/>
        KR,
        
        /// <remarks/>
        KW,
        
        /// <remarks/>
        KG,
        
        /// <remarks/>
        LA,
        
        /// <remarks/>
        LV,
        
        /// <remarks/>
        LB,
        
        /// <remarks/>
        LS,
        
        /// <remarks/>
        LR,
        
        /// <remarks/>
        LY,
        
        /// <remarks/>
        LI,
        
        /// <remarks/>
        LT,
        
        /// <remarks/>
        LU,
        
        /// <remarks/>
        MO,
        
        /// <remarks/>
        MK,
        
        /// <remarks/>
        MG,
        
        /// <remarks/>
        MW,
        
        /// <remarks/>
        MY,
        
        /// <remarks/>
        MV,
        
        /// <remarks/>
        ML,
        
        /// <remarks/>
        MT,
        
        /// <remarks/>
        MH,
        
        /// <remarks/>
        MQ,
        
        /// <remarks/>
        MR,
        
        /// <remarks/>
        MU,
        
        /// <remarks/>
        YT,
        
        /// <remarks/>
        MX,
        
        /// <remarks/>
        FM,
        
        /// <remarks/>
        MD,
        
        /// <remarks/>
        MC,
        
        /// <remarks/>
        MN,
        
        /// <remarks/>
        MS,
        
        /// <remarks/>
        MA,
        
        /// <remarks/>
        MZ,
        
        /// <remarks/>
        MM,
        
        /// <remarks/>
        NA,
        
        /// <remarks/>
        NR,
        
        /// <remarks/>
        NP,
        
        /// <remarks/>
        NL,
        
        /// <remarks/>
        AN,
        
        /// <remarks/>
        NC,
        
        /// <remarks/>
        NZ,
        
        /// <remarks/>
        NI,
        
        /// <remarks/>
        NE,
        
        /// <remarks/>
        NG,
        
        /// <remarks/>
        NU,
        
        /// <remarks/>
        NF,
        
        /// <remarks/>
        MP,
        
        /// <remarks/>
        NO,
        
        /// <remarks/>
        OM,
        
        /// <remarks/>
        PK,
        
        /// <remarks/>
        PW,
        
        /// <remarks/>
        PS,
        
        /// <remarks/>
        PA,
        
        /// <remarks/>
        PG,
        
        /// <remarks/>
        PY,
        
        /// <remarks/>
        PE,
        
        /// <remarks/>
        PH,
        
        /// <remarks/>
        PN,
        
        /// <remarks/>
        PL,
        
        /// <remarks/>
        PT,
        
        /// <remarks/>
        PR,
        
        /// <remarks/>
        QA,
        
        /// <remarks/>
        RE,
        
        /// <remarks/>
        RO,
        
        /// <remarks/>
        RU,
        
        /// <remarks/>
        RW,
        
        /// <remarks/>
        SH,
        
        /// <remarks/>
        KN,
        
        /// <remarks/>
        LC,
        
        /// <remarks/>
        PM,
        
        /// <remarks/>
        VC,
        
        /// <remarks/>
        WS,
        
        /// <remarks/>
        SM,
        
        /// <remarks/>
        ST,
        
        /// <remarks/>
        SA,
        
        /// <remarks/>
        SN,
        
        /// <remarks/>
        CS,
        
        /// <remarks/>
        SC,
        
        /// <remarks/>
        SL,
        
        /// <remarks/>
        SG,
        
        /// <remarks/>
        SK,
        
        /// <remarks/>
        SI,
        
        /// <remarks/>
        SB,
        
        /// <remarks/>
        SO,
        
        /// <remarks/>
        ZA,
        
        /// <remarks/>
        GS,
        
        /// <remarks/>
        ES,
        
        /// <remarks/>
        LK,
        
        /// <remarks/>
        SD,
        
        /// <remarks/>
        SR,
        
        /// <remarks/>
        SJ,
        
        /// <remarks/>
        SZ,
        
        /// <remarks/>
        SE,
        
        /// <remarks/>
        CH,
        
        /// <remarks/>
        SY,
        
        /// <remarks/>
        TW,
        
        /// <remarks/>
        TJ,
        
        /// <remarks/>
        TZ,
        
        /// <remarks/>
        TH,
        
        /// <remarks/>
        TL,
        
        /// <remarks/>
        TG,
        
        /// <remarks/>
        TK,
        
        /// <remarks/>
        TO,
        
        /// <remarks/>
        TT,
        
        /// <remarks/>
        TN,
        
        /// <remarks/>
        TR,
        
        /// <remarks/>
        TM,
        
        /// <remarks/>
        TC,
        
        /// <remarks/>
        TV,
        
        /// <remarks/>
        UG,
        
        /// <remarks/>
        UA,
        
        /// <remarks/>
        AE,
        
        /// <remarks/>
        GB,
        
        /// <remarks/>
        US,
        
        /// <remarks/>
        UM,
        
        /// <remarks/>
        UY,
        
        /// <remarks/>
        UZ,
        
        /// <remarks/>
        VU,
        
        /// <remarks/>
        VE,
        
        /// <remarks/>
        VN,
        
        /// <remarks/>
        VG,
        
        /// <remarks/>
        VI,
        
        /// <remarks/>
        WF,
        
        /// <remarks/>
        EH,
        
        /// <remarks/>
        YE,
        
        /// <remarks/>
        ZM,
        
        /// <remarks/>
        ZW,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/Inventory/2.0.0/SharedObjects/")]
    public partial class ArrayOfInventoryLocationInventoryLocationInventoryLocationQuantity {
        
        private ArrayOfInventoryLocationInventoryLocationInventoryLocationQuantityQuantity quantityField;
        
        /// <remarks/>
        public ArrayOfInventoryLocationInventoryLocationInventoryLocationQuantityQuantity Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/Inventory/2.0.0/SharedObjects/")]
    public partial class ArrayOfInventoryLocationInventoryLocationInventoryLocationQuantityQuantity {
        
        private QuantityUom uomField;
        
        private decimal valueField;
        
        /// <remarks/>
        public QuantityUom uom {
            get {
                return this.uomField;
            }
            set {
                this.uomField = value;
            }
        }
        
        /// <remarks/>
        public decimal value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/Inventory/2.0.0/SharedObjects/")]
    public partial class ArrayOfFutureAvailabilityFutureAvailability {
        
        private ArrayOfFutureAvailabilityFutureAvailabilityQuantity quantityField;
        
        private System.DateTime availableOnField;
        
        /// <remarks/>
        public ArrayOfFutureAvailabilityFutureAvailabilityQuantity Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime availableOn {
            get {
                return this.availableOnField;
            }
            set {
                this.availableOnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/Inventory/2.0.0/SharedObjects/")]
    public partial class ArrayOfFutureAvailabilityFutureAvailabilityQuantity {
        
        private QuantityUom uomField;
        
        private decimal valueField;
        
        /// <remarks/>
        public QuantityUom uom {
            get {
                return this.uomField;
            }
            set {
                this.uomField = value;
            }
        }
        
        /// <remarks/>
        public decimal value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void getFilterValuesCompletedEventHandler(object sender, getFilterValuesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getFilterValuesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getFilterValuesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetFilterValuesResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetFilterValuesResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void getInventoryLevelsCompletedEventHandler(object sender, getInventoryLevelsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getInventoryLevelsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getInventoryLevelsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetInventoryLevelsResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetInventoryLevelsResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591