//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SanMarIntegration.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ws.sanmar.com:8080/SanMarWebService/SanMarPricingServicePort")]
        public string SanMarIntegration_com_sanmar_ws_sanmarpricingserviceport_SanMarPricingServiceService {
            get {
                return ((string)(this["SanMarIntegration_com_sanmar_ws_sanmarpricingserviceport_SanMarPricingServiceServ" +
                    "ice"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ws.sanmar.com:8080/promostandards/PricingAndConfigurationServiceBinding")]
        public string SanMarIntegration_com_sanmar_ws_pricingandconfigurationservicebinding_PricingAndConfigurationService {
            get {
                return ((string)(this["SanMarIntegration_com_sanmar_ws_pricingandconfigurationservicebinding_PricingAndC" +
                    "onfigurationService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ws.sanmar.com:8080/SanMarWebService/SanMarProductInfoServicePort")]
        public string SanMarIntegration_com_sanmar_ws_sanmarproductinfoserviceport_SanMarProductInfoServiceService {
            get {
                return ((string)(this["SanMarIntegration_com_sanmar_ws_sanmarproductinfoserviceport_SanMarProductInfoSer" +
                    "viceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ws.sanmar.com:8080/promostandards/OrderShipmentNotificationServiceBinding" +
            "")]
        public string SanMarIntegration_com_sanmar_ws_ordershipmentnotificationservicebinding_OrderShipmentNotificationService {
            get {
                return ((string)(this["SanMarIntegration_com_sanmar_ws_ordershipmentnotificationservicebinding_OrderShip" +
                    "mentNotificationService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ws.sanmar.com:8080/promostandards/InventoryServiceBindingV2final")]
        public string SanMarIntegration_com_sanmar_ws_inventoryservicebindingvfinal_InventoryServiceV2final {
            get {
                return ((string)(this["SanMarIntegration_com_sanmar_ws_inventoryservicebindingvfinal_InventoryServiceV2f" +
                    "inal"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ws.sanmar.com:8080/promostandards/POServiceBinding")]
        public string SanMarIntegration_com_sanmar_ws_poservicebinding_POService {
            get {
                return ((string)(this["SanMarIntegration_com_sanmar_ws_poservicebinding_POService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ws.sanmar.com:8080/promostandards/OrderStatusServiceBinding")]
        public string SanMarIntegration_com_sanmar_ws_orderstatusservice_OrderStatusService {
            get {
                return ((string)(this["SanMarIntegration_com_sanmar_ws_orderstatusservice_OrderStatusService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ws.sanmar.com:8080/promostandards/InvoiceServiceBinding")]
        public string SanMarIntegration_com_sanmar_ws_invoiceservicebind_InvoiceService {
            get {
                return ((string)(this["SanMarIntegration_com_sanmar_ws_invoiceservicebind_InvoiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://edev-ws.sanmar.com:8080/promostandards/POServiceBinding")]
        public string SanMarIntegration_test_sm_poservicebinding_POService {
            get {
                return ((string)(this["SanMarIntegration_test_sm_poservicebinding_POService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://edev-ws.sanmar.com:8080/SanMarWebService/SanMarPricingServicePort")]
        public string SanMarIntegration_test_sm_pricingserviceport_SanMarPricingServiceService {
            get {
                return ((string)(this["SanMarIntegration_test_sm_pricingserviceport_SanMarPricingServiceService"]));
            }
        }
    }
}
