//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SanMarIntegration.com.sanmar.ws_invoiceservicebind {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="InvoiceServiceBinding", Namespace="http://www.promostandards.org/WSDL/Invoice/1.0.0/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InvoiceLineItem[]))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Invoice[]))]
    public partial class InvoiceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getInvoicesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public InvoiceService() {
            this.Url = global::SanMarIntegration.Properties.Settings.Default.SanMarIntegration_com_sanmar_ws_invoiceservicebind_InvoiceService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getInvoicesCompletedEventHandler getInvoicesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("getInvoices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetInvoicesResponse", Namespace="http://www.promostandards.org/WSDL/Invoice/1.0.0/")]
        public GetInvoicesResponse getInvoices([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/Invoice/1.0.0/")] GetInvoicesRequest GetInvoicesRequest) {
            object[] results = this.Invoke("getInvoices", new object[] {
                        GetInvoicesRequest});
            return ((GetInvoicesResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getInvoicesAsync(GetInvoicesRequest GetInvoicesRequest) {
            this.getInvoicesAsync(GetInvoicesRequest, null);
        }
        
        /// <remarks/>
        public void getInvoicesAsync(GetInvoicesRequest GetInvoicesRequest, object userState) {
            if ((this.getInvoicesOperationCompleted == null)) {
                this.getInvoicesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetInvoicesOperationCompleted);
            }
            this.InvokeAsync("getInvoices", new object[] {
                        GetInvoicesRequest}, this.getInvoicesOperationCompleted, userState);
        }
        
        private void OngetInvoicesOperationCompleted(object arg) {
            if ((this.getInvoicesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getInvoicesCompleted(this, new getInvoicesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/Invoice/1.0.0/")]
    public partial class GetInvoicesRequest {
        
        private string wsVersionField;
        
        private string idField;
        
        private string passwordField;
        
        private int queryTypeField;
        
        private string referenceNumberField;
        
        private System.DateTime invoiceRequestedDateField;
        
        private bool invoiceRequestedDateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/Invoice/1.0.0/SharedObjects/", DataType="token")]
        public string wsVersion {
            get {
                return this.wsVersionField;
            }
            set {
                this.wsVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/Invoice/1.0.0/SharedObjects/", DataType="token")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/Invoice/1.0.0/SharedObjects/", DataType="token")]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/Invoice/1.0.0/SharedObjects/")]
        public int queryType {
            get {
                return this.queryTypeField;
            }
            set {
                this.queryTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/Invoice/1.0.0/SharedObjects/")]
        public string referenceNumber {
            get {
                return this.referenceNumberField;
            }
            set {
                this.referenceNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/Invoice/1.0.0/SharedObjects/")]
        public System.DateTime invoiceRequestedDate {
            get {
                return this.invoiceRequestedDateField;
            }
            set {
                this.invoiceRequestedDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool invoiceRequestedDateSpecified {
            get {
                return this.invoiceRequestedDateFieldSpecified;
            }
            set {
                this.invoiceRequestedDateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/Invoice/1.0.0/SharedObjects/")]
    public partial class InvoiceLineItem {
        
        private int invoiceLineItemIdField;
        
        private decimal invoiceLineItemNumberField;
        
        private bool invoiceLineItemNumberFieldSpecified;
        
        private decimal purchaseOrderLineItemNumberField;
        
        private bool purchaseOrderLineItemNumberFieldSpecified;
        
        private lineItemType lineItemTypeField;
        
        private decimal orderedQuantityField;
        
        private bool orderedQuantityFieldSpecified;
        
        private decimal invoiceQuantityField;
        
        private decimal backOrderedQuantityField;
        
        private bool backOrderedQuantityFieldSpecified;
        
        private string quantityUOMField;
        
        private string lineItemDescriptionField;
        
        private decimal unitPriceField;
        
        private decimal extendedPriceField;
        
        private bool lineItemTaxField;
        
        private lineItemTaxType lineItemTaxTypeField;
        
        private bool lineItemTaxTypeFieldSpecified;
        
        /// <remarks/>
        public int invoiceLineItemId {
            get {
                return this.invoiceLineItemIdField;
            }
            set {
                this.invoiceLineItemIdField = value;
            }
        }
        
        /// <remarks/>
        public decimal invoiceLineItemNumber {
            get {
                return this.invoiceLineItemNumberField;
            }
            set {
                this.invoiceLineItemNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool invoiceLineItemNumberSpecified {
            get {
                return this.invoiceLineItemNumberFieldSpecified;
            }
            set {
                this.invoiceLineItemNumberFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal purchaseOrderLineItemNumber {
            get {
                return this.purchaseOrderLineItemNumberField;
            }
            set {
                this.purchaseOrderLineItemNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool purchaseOrderLineItemNumberSpecified {
            get {
                return this.purchaseOrderLineItemNumberFieldSpecified;
            }
            set {
                this.purchaseOrderLineItemNumberFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public lineItemType lineItemType {
            get {
                return this.lineItemTypeField;
            }
            set {
                this.lineItemTypeField = value;
            }
        }
        
        /// <remarks/>
        public decimal orderedQuantity {
            get {
                return this.orderedQuantityField;
            }
            set {
                this.orderedQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool orderedQuantitySpecified {
            get {
                return this.orderedQuantityFieldSpecified;
            }
            set {
                this.orderedQuantityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal invoiceQuantity {
            get {
                return this.invoiceQuantityField;
            }
            set {
                this.invoiceQuantityField = value;
            }
        }
        
        /// <remarks/>
        public decimal backOrderedQuantity {
            get {
                return this.backOrderedQuantityField;
            }
            set {
                this.backOrderedQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool backOrderedQuantitySpecified {
            get {
                return this.backOrderedQuantityFieldSpecified;
            }
            set {
                this.backOrderedQuantityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string quantityUOM {
            get {
                return this.quantityUOMField;
            }
            set {
                this.quantityUOMField = value;
            }
        }
        
        /// <remarks/>
        public string lineItemDescription {
            get {
                return this.lineItemDescriptionField;
            }
            set {
                this.lineItemDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public decimal unitPrice {
            get {
                return this.unitPriceField;
            }
            set {
                this.unitPriceField = value;
            }
        }
        
        /// <remarks/>
        public decimal extendedPrice {
            get {
                return this.extendedPriceField;
            }
            set {
                this.extendedPriceField = value;
            }
        }
        
        /// <remarks/>
        public bool lineItemTax {
            get {
                return this.lineItemTaxField;
            }
            set {
                this.lineItemTaxField = value;
            }
        }
        
        /// <remarks/>
        public lineItemTaxType lineItemTaxType {
            get {
                return this.lineItemTaxTypeField;
            }
            set {
                this.lineItemTaxTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lineItemTaxTypeSpecified {
            get {
                return this.lineItemTaxTypeFieldSpecified;
            }
            set {
                this.lineItemTaxTypeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.promostandards.org/WSDL/Invoice/1.0.0/SharedObjects/")]
    public enum lineItemType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("LINE ITEM")]
        LINEITEM,
        
        /// <remarks/>
        TAX,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.promostandards.org/WSDL/Invoice/1.0.0/SharedObjects/")]
    public enum lineItemTaxType {
        
        /// <remarks/>
        SALES,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("HST/GST")]
        HSTGST,
        
        /// <remarks/>
        PST,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/Invoice/1.0.0/")]
    public partial class Invoice {
        
        private string invoiceNumberField;
        
        private invoiceType invoiceTypeField;
        
        private System.DateTime invoiceDateField;
        
        private string purchaseOrderNumberField;
        
        private InvoiceBillTo billToField;
        
        private InvoiceSoldTo soldToField;
        
        private string termsField;
        
        private CurrencyCodeType currencyField;
        
        private bool currencyFieldSpecified;
        
        private string fobField;
        
        private decimal salesAmountField;
        
        private decimal totalAmountField;
        
        private decimal shippingAndHandlingAmountField;
        
        private decimal advancePaymentAmountField;
        
        private decimal invoiceAmountField;
        
        private InvoiceLineItem[] invoiceLineItemsArrayField;
        
        private string[] salesOrderNumberArrayField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/Invoice/1.0.0/SharedObjects/", DataType="token")]
        public string invoiceNumber {
            get {
                return this.invoiceNumberField;
            }
            set {
                this.invoiceNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/Invoice/1.0.0/SharedObjects/")]
        public invoiceType invoiceType {
            get {
                return this.invoiceTypeField;
            }
            set {
                this.invoiceTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/Invoice/1.0.0/SharedObjects/")]
        public System.DateTime invoiceDate {
            get {
                return this.invoiceDateField;
            }
            set {
                this.invoiceDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/Invoice/1.0.0/SharedObjects/")]
        public string purchaseOrderNumber {
            get {
                return this.purchaseOrderNumberField;
            }
            set {
                this.purchaseOrderNumberField = value;
            }
        }
        
        /// <remarks/>
        public InvoiceBillTo BillTo {
            get {
                return this.billToField;
            }
            set {
                this.billToField = value;
            }
        }
        
        /// <remarks/>
        public InvoiceSoldTo SoldTo {
            get {
                return this.soldToField;
            }
            set {
                this.soldToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/Invoice/1.0.0/SharedObjects/")]
        public string terms {
            get {
                return this.termsField;
            }
            set {
                this.termsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/Invoice/1.0.0/SharedObjects/")]
        public CurrencyCodeType currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool currencySpecified {
            get {
                return this.currencyFieldSpecified;
            }
            set {
                this.currencyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/Invoice/1.0.0/SharedObjects/", DataType="token")]
        public string fob {
            get {
                return this.fobField;
            }
            set {
                this.fobField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/Invoice/1.0.0/SharedObjects/")]
        public decimal salesAmount {
            get {
                return this.salesAmountField;
            }
            set {
                this.salesAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/Invoice/1.0.0/SharedObjects/")]
        public decimal totalAmount {
            get {
                return this.totalAmountField;
            }
            set {
                this.totalAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/Invoice/1.0.0/SharedObjects/")]
        public decimal shippingAndHandlingAmount {
            get {
                return this.shippingAndHandlingAmountField;
            }
            set {
                this.shippingAndHandlingAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/Invoice/1.0.0/SharedObjects/")]
        public decimal advancePaymentAmount {
            get {
                return this.advancePaymentAmountField;
            }
            set {
                this.advancePaymentAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/Invoice/1.0.0/SharedObjects/")]
        public decimal invoiceAmount {
            get {
                return this.invoiceAmountField;
            }
            set {
                this.invoiceAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("InvoiceLineItem", Namespace="http://www.promostandards.org/WSDL/Invoice/1.0.0/SharedObjects/", IsNullable=false)]
        public InvoiceLineItem[] InvoiceLineItemsArray {
            get {
                return this.invoiceLineItemsArrayField;
            }
            set {
                this.invoiceLineItemsArrayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("salesOrderNumber", Namespace="http://www.promostandards.org/WSDL/Invoice/1.0.0/SharedObjects/", IsNullable=false)]
        public string[] SalesOrderNumberArray {
            get {
                return this.salesOrderNumberArrayField;
            }
            set {
                this.salesOrderNumberArrayField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.promostandards.org/WSDL/Invoice/1.0.0/SharedObjects/")]
    public enum invoiceType {
        
        /// <remarks/>
        INVOICE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("CREDIT MEMO")]
        CREDITMEMO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/Invoice/1.0.0/")]
    public partial class InvoiceBillTo {
        
        private AccountInfo accountInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/Invoice/1.0.0/SharedObjects/")]
        public AccountInfo AccountInfo {
            get {
                return this.accountInfoField;
            }
            set {
                this.accountInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/Invoice/1.0.0/SharedObjects/")]
    public partial class AccountInfo {
        
        private string accountNameField;
        
        private string accountNumberField;
        
        private string[] addressLinesArrayField;
        
        private string cityField;
        
        private string stateField;
        
        private string postalCodeField;
        
        /// <remarks/>
        public string accountName {
            get {
                return this.accountNameField;
            }
            set {
                this.accountNameField = value;
            }
        }
        
        /// <remarks/>
        public string accountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                this.accountNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AddressLinesArray")]
        public string[] AddressLinesArray {
            get {
                return this.addressLinesArrayField;
            }
            set {
                this.addressLinesArrayField = value;
            }
        }
        
        /// <remarks/>
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string postalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/Invoice/1.0.0/")]
    public partial class InvoiceSoldTo {
        
        private AccountInfo accountInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/Invoice/1.0.0/SharedObjects/")]
        public AccountInfo AccountInfo {
            get {
                return this.accountInfoField;
            }
            set {
                this.accountInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.isotc211.org/iso4217/")]
    public enum CurrencyCodeType {
        
        /// <remarks/>
        AFA,
        
        /// <remarks/>
        ALL,
        
        /// <remarks/>
        DZD,
        
        /// <remarks/>
        AON,
        
        /// <remarks/>
        ARS,
        
        /// <remarks/>
        AMD,
        
        /// <remarks/>
        AWG,
        
        /// <remarks/>
        AUD,
        
        /// <remarks/>
        ATS,
        
        /// <remarks/>
        AZM,
        
        /// <remarks/>
        BSD,
        
        /// <remarks/>
        BHD,
        
        /// <remarks/>
        BDT,
        
        /// <remarks/>
        BBD,
        
        /// <remarks/>
        BYR,
        
        /// <remarks/>
        BEF,
        
        /// <remarks/>
        BZD,
        
        /// <remarks/>
        BMD,
        
        /// <remarks/>
        BTN,
        
        /// <remarks/>
        BOB,
        
        /// <remarks/>
        BAM,
        
        /// <remarks/>
        BWP,
        
        /// <remarks/>
        BRL,
        
        /// <remarks/>
        BND,
        
        /// <remarks/>
        BGL,
        
        /// <remarks/>
        BIF,
        
        /// <remarks/>
        KHR,
        
        /// <remarks/>
        CAD,
        
        /// <remarks/>
        CVE,
        
        /// <remarks/>
        KYD,
        
        /// <remarks/>
        XOF,
        
        /// <remarks/>
        XAF,
        
        /// <remarks/>
        XPF,
        
        /// <remarks/>
        CLP,
        
        /// <remarks/>
        CNY,
        
        /// <remarks/>
        COP,
        
        /// <remarks/>
        KMF,
        
        /// <remarks/>
        CDF,
        
        /// <remarks/>
        CRC,
        
        /// <remarks/>
        HRK,
        
        /// <remarks/>
        CUP,
        
        /// <remarks/>
        CYP,
        
        /// <remarks/>
        CZK,
        
        /// <remarks/>
        DKK,
        
        /// <remarks/>
        DEM,
        
        /// <remarks/>
        DJF,
        
        /// <remarks/>
        DOP,
        
        /// <remarks/>
        NLG,
        
        /// <remarks/>
        XCD,
        
        /// <remarks/>
        ECS,
        
        /// <remarks/>
        EGP,
        
        /// <remarks/>
        SVC,
        
        /// <remarks/>
        ERN,
        
        /// <remarks/>
        EEK,
        
        /// <remarks/>
        ETB,
        
        /// <remarks/>
        EUR,
        
        /// <remarks/>
        FKP,
        
        /// <remarks/>
        FJD,
        
        /// <remarks/>
        FIM,
        
        /// <remarks/>
        FRF,
        
        /// <remarks/>
        GMD,
        
        /// <remarks/>
        GEL,
        
        /// <remarks/>
        GHC,
        
        /// <remarks/>
        GIP,
        
        /// <remarks/>
        GRD,
        
        /// <remarks/>
        GTQ,
        
        /// <remarks/>
        GYD,
        
        /// <remarks/>
        HTG,
        
        /// <remarks/>
        HNL,
        
        /// <remarks/>
        HKD,
        
        /// <remarks/>
        HUF,
        
        /// <remarks/>
        ISK,
        
        /// <remarks/>
        INR,
        
        /// <remarks/>
        IDR,
        
        /// <remarks/>
        IRR,
        
        /// <remarks/>
        IQD,
        
        /// <remarks/>
        IEP,
        
        /// <remarks/>
        ILS,
        
        /// <remarks/>
        ITL,
        
        /// <remarks/>
        JMD,
        
        /// <remarks/>
        JPY,
        
        /// <remarks/>
        JOD,
        
        /// <remarks/>
        KZT,
        
        /// <remarks/>
        KES,
        
        /// <remarks/>
        KWD,
        
        /// <remarks/>
        KGS,
        
        /// <remarks/>
        LAK,
        
        /// <remarks/>
        LVL,
        
        /// <remarks/>
        LBP,
        
        /// <remarks/>
        LSL,
        
        /// <remarks/>
        LRD,
        
        /// <remarks/>
        LYD,
        
        /// <remarks/>
        LTL,
        
        /// <remarks/>
        LUF,
        
        /// <remarks/>
        MOP,
        
        /// <remarks/>
        MKD,
        
        /// <remarks/>
        MGF,
        
        /// <remarks/>
        MWK,
        
        /// <remarks/>
        MYR,
        
        /// <remarks/>
        MVR,
        
        /// <remarks/>
        MTL,
        
        /// <remarks/>
        MRO,
        
        /// <remarks/>
        MUR,
        
        /// <remarks/>
        MXN,
        
        /// <remarks/>
        MDL,
        
        /// <remarks/>
        MNT,
        
        /// <remarks/>
        MAD,
        
        /// <remarks/>
        MZM,
        
        /// <remarks/>
        MMK,
        
        /// <remarks/>
        NAD,
        
        /// <remarks/>
        NPR,
        
        /// <remarks/>
        ANG,
        
        /// <remarks/>
        ZRN,
        
        /// <remarks/>
        NZD,
        
        /// <remarks/>
        NIC,
        
        /// <remarks/>
        NGN,
        
        /// <remarks/>
        KPW,
        
        /// <remarks/>
        NOK,
        
        /// <remarks/>
        PKR,
        
        /// <remarks/>
        PAB,
        
        /// <remarks/>
        PGK,
        
        /// <remarks/>
        PYG,
        
        /// <remarks/>
        PEN,
        
        /// <remarks/>
        PHP,
        
        /// <remarks/>
        PLN,
        
        /// <remarks/>
        PTE,
        
        /// <remarks/>
        QAR,
        
        /// <remarks/>
        OMR,
        
        /// <remarks/>
        ROL,
        
        /// <remarks/>
        RUR,
        
        /// <remarks/>
        RWF,
        
        /// <remarks/>
        STD,
        
        /// <remarks/>
        SAR,
        
        /// <remarks/>
        SCR,
        
        /// <remarks/>
        SLL,
        
        /// <remarks/>
        SGD,
        
        /// <remarks/>
        SKK,
        
        /// <remarks/>
        SIT,
        
        /// <remarks/>
        SBD,
        
        /// <remarks/>
        SOS,
        
        /// <remarks/>
        ZAR,
        
        /// <remarks/>
        KRW,
        
        /// <remarks/>
        ESP,
        
        /// <remarks/>
        LKR,
        
        /// <remarks/>
        SHP,
        
        /// <remarks/>
        GBP,
        
        /// <remarks/>
        SDP,
        
        /// <remarks/>
        SRG,
        
        /// <remarks/>
        SZL,
        
        /// <remarks/>
        SEK,
        
        /// <remarks/>
        CHF,
        
        /// <remarks/>
        SYP,
        
        /// <remarks/>
        TWD,
        
        /// <remarks/>
        TJR,
        
        /// <remarks/>
        TZS,
        
        /// <remarks/>
        THB,
        
        /// <remarks/>
        TPE,
        
        /// <remarks/>
        TOP,
        
        /// <remarks/>
        TTD,
        
        /// <remarks/>
        TND,
        
        /// <remarks/>
        TRL,
        
        /// <remarks/>
        TMM,
        
        /// <remarks/>
        AED,
        
        /// <remarks/>
        UGX,
        
        /// <remarks/>
        UAH,
        
        /// <remarks/>
        UYU,
        
        /// <remarks/>
        USD,
        
        /// <remarks/>
        UZS,
        
        /// <remarks/>
        VUV,
        
        /// <remarks/>
        VEB,
        
        /// <remarks/>
        VND,
        
        /// <remarks/>
        WST,
        
        /// <remarks/>
        YER,
        
        /// <remarks/>
        YUM,
        
        /// <remarks/>
        ZMK,
        
        /// <remarks/>
        ZWD,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/Invoice/1.0.0/")]
    public partial class GetInvoicesResponse {
        
        private Invoice[] invoiceArrayField;
        
        private ErrorMessage errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Invoice", IsNullable=false)]
        public Invoice[] InvoiceArray {
            get {
                return this.invoiceArrayField;
            }
            set {
                this.invoiceArrayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/Invoice/1.0.0/SharedObjects/")]
        public ErrorMessage ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/Invoice/1.0.0/SharedObjects/")]
    public partial class ErrorMessage {
        
        private int codeField;
        
        private string descriptionField;
        
        /// <remarks/>
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void getInvoicesCompletedEventHandler(object sender, getInvoicesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getInvoicesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getInvoicesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetInvoicesResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetInvoicesResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591